### ISSUE TITLE
Use execFileSync or similar passing the arguments as arrays instead of a single command string

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-telemetry-extractor#21]
The extraction code fails on windows and other platforms

Here's the error message from windows
```
Error: 'publicLogError2'' is not recognized as an internal or external command,
operable program or batch file.
```

I managed to get this working on Windows by changing the following code
```const text = "const retrieved_paths = cp.execSync(cmd, { encoding: 'ascii' });";```
to 
```const retrieved_paths = cp.execFileSync(ripgrep_1.rgPath, ['--files-with-matches', '--glob', '**/*.ts', '--no-ignore', 'publicLog2|publicLogError2', this.sourceDir], { encoding: 'ascii' });";```

With the former some how `publicLogError2` ends up as a piping operation, I guess the character `|` some how triggers that behaviour (possible due to incorrectly escaped arguments or the like).

I would suggest changing this everywhere where we use `execSync`
Also would suggest logging the errors, today the errors are swallowed, and its possible we're ignoring all such errors due to the empty `catch { }`.

**Comment by lramos15** [comment]
> Also would suggest logging the errors, today the errors are swallowed, and its possible we're ignoring all such errors due to the empty `catch { }`.

The reason for this is that ripgrep throws a non zero exit code with an obscure error if no matches are found. Logging the error won't be helpful

**Comment by DonJayamanne** [comment]
Agreed, but we would have identified this windows error if we had logged the error
